name: strapen_app
description: Strapen um aplicativo para gerenciamento de Live Shop.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  brasil_fields: ^1.1.4
  carousel_slider: ^4.0.0
  connectivity_plus: ^1.0.8
  cupertino_icons: ^1.0.3
  flutter_dotenv: ^5.0.2
  flutter_mobx: ^2.0.2
  flutter_modular: ^3.3.1
  flutter_svg: ^0.22.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.3+3
  intl: ^0.17.0
  mobx: ^2.0.4
  parse_server_sdk_flutter: ^3.1.0
  shared_preferences: ^2.0.6
  snapping_sheet: ^3.1.0

  camera_with_rtmp:
    git:
      url: git@github.com:GabrielDimaa/flutter_rtmppublisher.git
      ref: master

dev_dependencies:
  build_runner: ^2.1.1
  mobx_codegen: ^2.0.1+3
  modular_codegen: ^3.0.2


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/garota_tirando_selfie.png
    - assets/images/escrevendo_pc.png
    - assets/images/mulher_exibindo_manequim.png
    - assets/images/mulher_mexendo_mural.png
    - assets/images/test/avatar_test.png
    - assets/images/empty_produtos.svg

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100


## Slidy Scripts
vars:
  get: flutter pub get
  clean: flutter clean
  runner: flutter pub run build_runner

scripts:
  mobx: $runner watch
  mobx_restart: $get & $runner watch --delete-conflicting-outputs
  clean: $clean & $get